version: "3.2"
services:
  qrcode:
    build: .
    stdin_open: true
    tty: true
    environment:
      QR_CODE_IMAGE_DIRECTORY: 'images'
      QR_CODE_DEFAULT_URL: 'https://hub.docker.com/repository/docker/dombino/isqrcode'
      QR_CODE_DEFAULT_FILE_NAME: 'domurso-docker.png'
    volumes:
      - .:/home/myuser
